apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysvc
  name: mysvc
spec:
  ports:
  - name: "mysvc"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  type: LoadBalancer
